// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#include "process.h"


__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("print-to-terminal")))
extern void __wasm_import_uqbar_process_0_4_0_standard_print_to_terminal(int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("get-eth-block")))
extern int64_t __wasm_import_uqbar_process_0_4_0_standard_get_eth_block(void);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("set-on-panic")))
extern void __wasm_import_uqbar_process_0_4_0_standard_set_on_panic(int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("get-state")))
extern void __wasm_import_uqbar_process_0_4_0_standard_get_state(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("set-state")))
extern void __wasm_import_uqbar_process_0_4_0_standard_set_state(int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("clear-state")))
extern void __wasm_import_uqbar_process_0_4_0_standard_clear_state(void);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("spawn")))
extern void __wasm_import_uqbar_process_0_4_0_standard_spawn(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("get-capabilities")))
extern void __wasm_import_uqbar_process_0_4_0_standard_get_capabilities(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("get-capability")))
extern void __wasm_import_uqbar_process_0_4_0_standard_get_capability(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("attach-capability")))
extern void __wasm_import_uqbar_process_0_4_0_standard_attach_capability(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("save-capabilities")))
extern void __wasm_import_uqbar_process_0_4_0_standard_save_capabilities(int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("has-capability")))
extern int32_t __wasm_import_uqbar_process_0_4_0_standard_has_capability(int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("create-capability")))
extern void __wasm_import_uqbar_process_0_4_0_standard_create_capability(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("share-capability")))
extern void __wasm_import_uqbar_process_0_4_0_standard_share_capability(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("receive")))
extern void __wasm_import_uqbar_process_0_4_0_standard_receive(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("get-payload")))
extern void __wasm_import_uqbar_process_0_4_0_standard_get_payload(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("send-request")))
extern void __wasm_import_uqbar_process_0_4_0_standard_send_request(int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("send-requests")))
extern void __wasm_import_uqbar_process_0_4_0_standard_send_requests(int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("send-response")))
extern void __wasm_import_uqbar_process_0_4_0_standard_send_response(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("uqbar:process/standard@0.4.0"), __import_name__("send-and-await-response")))
extern void __wasm_import_uqbar_process_0_4_0_standard_send_and_await_response(int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void uqbar_process_0_4_0_standard_json_free(uqbar_process_0_4_0_standard_json_t *ptr) {
  process_string_free(ptr);
}

void uqbar_process_0_4_0_standard_node_id_free(uqbar_process_0_4_0_standard_node_id_t *ptr) {
  process_string_free(ptr);
}

void uqbar_process_0_4_0_standard_context_free(uqbar_process_0_4_0_standard_context_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void uqbar_process_0_4_0_standard_process_id_free(uqbar_process_0_4_0_standard_process_id_t *ptr) {
  process_string_free(&ptr->process_name);
  process_string_free(&ptr->package_name);
  uqbar_process_0_4_0_standard_node_id_free(&ptr->publisher_node);
}

void uqbar_process_0_4_0_standard_address_free(uqbar_process_0_4_0_standard_address_t *ptr) {
  uqbar_process_0_4_0_standard_node_id_free(&ptr->node);
  uqbar_process_0_4_0_standard_process_id_free(&ptr->process);
}

void process_option_string_free(process_option_string_t *ptr) {
  if (ptr->is_some) {
    process_string_free(&ptr->val);
  }
}

void process_list_u8_free(process_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void uqbar_process_0_4_0_standard_payload_free(uqbar_process_0_4_0_standard_payload_t *ptr) {
  process_option_string_free(&ptr->mime);
  process_list_u8_free(&ptr->bytes);
}

void process_option_u64_free(process_option_u64_t *ptr) {
  if (ptr->is_some) {
  }
}

void process_option_json_free(process_option_json_t *ptr) {
  if (ptr->is_some) {
    uqbar_process_0_4_0_standard_json_free(&ptr->val);
  }
}

void uqbar_process_0_4_0_standard_request_free(uqbar_process_0_4_0_standard_request_t *ptr) {
  process_option_u64_free(&ptr->expects_response);
  process_list_u8_free(&ptr->ipc);
  process_option_json_free(&ptr->metadata);
}

void uqbar_process_0_4_0_standard_response_free(uqbar_process_0_4_0_standard_response_t *ptr) {
  process_list_u8_free(&ptr->ipc);
  process_option_json_free(&ptr->metadata);
}

void process_option_context_free(process_option_context_t *ptr) {
  if (ptr->is_some) {
    uqbar_process_0_4_0_standard_context_free(&ptr->val);
  }
}

void uqbar_process_0_4_0_standard_tuple2_response_option_context_free(uqbar_process_0_4_0_standard_tuple2_response_option_context_t *ptr) {
  uqbar_process_0_4_0_standard_response_free(&ptr->f0);
  process_option_context_free(&ptr->f1);
}

void uqbar_process_0_4_0_standard_message_free(uqbar_process_0_4_0_standard_message_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      uqbar_process_0_4_0_standard_request_free(&ptr->val.request);
      break;
    }
    case 1: {
      uqbar_process_0_4_0_standard_tuple2_response_option_context_free(&ptr->val.response);
      break;
    }
  }
}

void uqbar_process_0_4_0_standard_signed_capability_free(uqbar_process_0_4_0_standard_signed_capability_t *ptr) {
  uqbar_process_0_4_0_standard_address_free(&ptr->issuer);
  uqbar_process_0_4_0_standard_json_free(&ptr->params);
  process_list_u8_free(&ptr->signature);
}

void uqbar_process_0_4_0_standard_list_signed_capability_free(uqbar_process_0_4_0_standard_list_signed_capability_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    uqbar_process_0_4_0_standard_signed_capability_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void uqbar_process_0_4_0_standard_capabilities_free(uqbar_process_0_4_0_standard_capabilities_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      uqbar_process_0_4_0_standard_list_signed_capability_free(&ptr->val.some);
      break;
    }
  }
}

void uqbar_process_0_4_0_standard_option_payload_free(uqbar_process_0_4_0_standard_option_payload_t *ptr) {
  if (ptr->is_some) {
    uqbar_process_0_4_0_standard_payload_free(&ptr->val);
  }
}

void uqbar_process_0_4_0_standard_tuple3_address_request_option_payload_free(uqbar_process_0_4_0_standard_tuple3_address_request_option_payload_t *ptr) {
  uqbar_process_0_4_0_standard_address_free(&ptr->f0);
  uqbar_process_0_4_0_standard_request_free(&ptr->f1);
  uqbar_process_0_4_0_standard_option_payload_free(&ptr->f2);
}

void uqbar_process_0_4_0_standard_list_tuple3_address_request_option_payload_free(uqbar_process_0_4_0_standard_list_tuple3_address_request_option_payload_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    uqbar_process_0_4_0_standard_tuple3_address_request_option_payload_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void uqbar_process_0_4_0_standard_on_panic_free(uqbar_process_0_4_0_standard_on_panic_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      uqbar_process_0_4_0_standard_list_tuple3_address_request_option_payload_free(&ptr->val.requests);
      break;
    }
  }
}

void uqbar_process_0_4_0_standard_send_error_free(uqbar_process_0_4_0_standard_send_error_t *ptr) {
  uqbar_process_0_4_0_standard_message_free(&ptr->message);
  uqbar_process_0_4_0_standard_option_payload_free(&ptr->payload);
}

void process_option_list_u8_free(process_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    process_list_u8_free(&ptr->val);
  }
}

void uqbar_process_0_4_0_standard_result_process_id_spawn_error_free(uqbar_process_0_4_0_standard_result_process_id_spawn_error_t *ptr) {
  if (!ptr->is_err) {
    uqbar_process_0_4_0_standard_process_id_free(&ptr->val.ok);
  } else {
  }
}

void uqbar_process_0_4_0_standard_option_signed_capability_free(uqbar_process_0_4_0_standard_option_signed_capability_t *ptr) {
  if (ptr->is_some) {
    uqbar_process_0_4_0_standard_signed_capability_free(&ptr->val);
  }
}

void uqbar_process_0_4_0_standard_tuple2_address_message_free(uqbar_process_0_4_0_standard_tuple2_address_message_t *ptr) {
  uqbar_process_0_4_0_standard_address_free(&ptr->f0);
  uqbar_process_0_4_0_standard_message_free(&ptr->f1);
}

void uqbar_process_0_4_0_standard_tuple2_send_error_option_context_free(uqbar_process_0_4_0_standard_tuple2_send_error_option_context_t *ptr) {
  uqbar_process_0_4_0_standard_send_error_free(&ptr->f0);
  process_option_context_free(&ptr->f1);
}

void uqbar_process_0_4_0_standard_result_tuple2_address_message_tuple2_send_error_option_context_free(uqbar_process_0_4_0_standard_result_tuple2_address_message_tuple2_send_error_option_context_t *ptr) {
  if (!ptr->is_err) {
    uqbar_process_0_4_0_standard_tuple2_address_message_free(&ptr->val.ok);
  } else {
    uqbar_process_0_4_0_standard_tuple2_send_error_option_context_free(&ptr->val.err);
  }
}

void uqbar_process_0_4_0_standard_tuple4_address_request_option_context_option_payload_free(uqbar_process_0_4_0_standard_tuple4_address_request_option_context_option_payload_t *ptr) {
  uqbar_process_0_4_0_standard_address_free(&ptr->f0);
  uqbar_process_0_4_0_standard_request_free(&ptr->f1);
  process_option_context_free(&ptr->f2);
  uqbar_process_0_4_0_standard_option_payload_free(&ptr->f3);
}

void uqbar_process_0_4_0_standard_list_tuple4_address_request_option_context_option_payload_free(uqbar_process_0_4_0_standard_list_tuple4_address_request_option_context_option_payload_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    uqbar_process_0_4_0_standard_tuple4_address_request_option_context_option_payload_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void uqbar_process_0_4_0_standard_result_tuple2_address_message_send_error_free(uqbar_process_0_4_0_standard_result_tuple2_address_message_send_error_t *ptr) {
  if (!ptr->is_err) {
    uqbar_process_0_4_0_standard_tuple2_address_message_free(&ptr->val.ok);
  } else {
    uqbar_process_0_4_0_standard_send_error_free(&ptr->val.err);
  }
}

void process_string_set(process_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void process_string_dup(process_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void process_string_free(process_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void uqbar_process_0_4_0_standard_print_to_terminal(uint8_t verbosity, process_string_t *message) {
  __wasm_import_uqbar_process_0_4_0_standard_print_to_terminal((int32_t) (verbosity), (int32_t) (*message).ptr, (int32_t) (*message).len);
}

uint64_t uqbar_process_0_4_0_standard_get_eth_block(void) {
  int64_t ret = __wasm_import_uqbar_process_0_4_0_standard_get_eth_block();
  return (uint64_t) (ret);
}

void uqbar_process_0_4_0_standard_set_on_panic(uqbar_process_0_4_0_standard_on_panic_t *on_panic) {
  int32_t variant;
  int32_t variant10;
  int32_t variant11;
  switch ((int32_t) (*on_panic).tag) {
    case 0: {
      variant = 0;
      variant10 = 0;
      variant11 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant10 = 0;
      variant11 = 0;
      break;
    }
    case 2: {
      const uqbar_process_0_4_0_standard_list_tuple3_address_request_option_payload_t *payload1 = &(*on_panic).val.requests;
      variant = 2;
      variant10 = (int32_t) (*payload1).ptr;
      variant11 = (int32_t) (*payload1).len;
      break;
    }
  }
  __wasm_import_uqbar_process_0_4_0_standard_set_on_panic(variant, variant10, variant11);
}

void uqbar_process_0_4_0_standard_get_state(process_option_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_get_state(ptr);
  process_option_list_u8_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

void uqbar_process_0_4_0_standard_set_state(process_list_u8_t *bytes) {
  __wasm_import_uqbar_process_0_4_0_standard_set_state((int32_t) (*bytes).ptr, (int32_t) (*bytes).len);
}

void uqbar_process_0_4_0_standard_clear_state(void) {
  __wasm_import_uqbar_process_0_4_0_standard_clear_state();
}

void uqbar_process_0_4_0_standard_spawn(process_option_string_t *name, process_string_t *wasm_path, uqbar_process_0_4_0_standard_on_panic_t *on_panic, uqbar_process_0_4_0_standard_capabilities_t *capabilities, bool public_, uqbar_process_0_4_0_standard_result_process_id_spawn_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[28];
  int32_t option;
  int32_t option1;
  int32_t option2;
  if ((*name).is_some) {
    const process_string_t *payload0 = &(*name).val;
    option = 1;
    option1 = (int32_t) (*payload0).ptr;
    option2 = (int32_t) (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t variant;
  int32_t variant14;
  int32_t variant15;
  switch ((int32_t) (*on_panic).tag) {
    case 0: {
      variant = 0;
      variant14 = 0;
      variant15 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant14 = 0;
      variant15 = 0;
      break;
    }
    case 2: {
      const uqbar_process_0_4_0_standard_list_tuple3_address_request_option_payload_t *payload5 = &(*on_panic).val.requests;
      variant = 2;
      variant14 = (int32_t) (*payload5).ptr;
      variant15 = (int32_t) (*payload5).len;
      break;
    }
  }
  int32_t variant19;
  int32_t variant20;
  int32_t variant21;
  switch ((int32_t) (*capabilities).tag) {
    case 0: {
      variant19 = 0;
      variant20 = 0;
      variant21 = 0;
      break;
    }
    case 1: {
      variant19 = 1;
      variant20 = 0;
      variant21 = 0;
      break;
    }
    case 2: {
      const uqbar_process_0_4_0_standard_list_signed_capability_t *payload18 = &(*capabilities).val.some;
      variant19 = 2;
      variant20 = (int32_t) (*payload18).ptr;
      variant21 = (int32_t) (*payload18).len;
      break;
    }
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_spawn(option, option1, option2, (int32_t) (*wasm_path).ptr, (int32_t) (*wasm_path).len, variant, variant14, variant15, variant19, variant20, variant21, public_, ptr);
  uqbar_process_0_4_0_standard_result_process_id_spawn_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uqbar_process_0_4_0_standard_process_id_t) {
        (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) },
        (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 20))), (size_t)(*((int32_t*) (ptr + 24))) },
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void uqbar_process_0_4_0_standard_get_capabilities(uqbar_process_0_4_0_standard_list_signed_capability_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_get_capabilities(ptr);
  *ret = (uqbar_process_0_4_0_standard_list_signed_capability_t) { (uqbar_process_0_4_0_standard_signed_capability_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void uqbar_process_0_4_0_standard_get_capability(uqbar_process_0_4_0_standard_address_t *issuer, uqbar_process_0_4_0_standard_json_t *params, uqbar_process_0_4_0_standard_option_signed_capability_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[52];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_get_capability((int32_t) ((*issuer).node).ptr, (int32_t) ((*issuer).node).len, (int32_t) (((*issuer).process).process_name).ptr, (int32_t) (((*issuer).process).process_name).len, (int32_t) (((*issuer).process).package_name).ptr, (int32_t) (((*issuer).process).package_name).len, (int32_t) (((*issuer).process).publisher_node).ptr, (int32_t) (((*issuer).process).publisher_node).len, (int32_t) (*params).ptr, (int32_t) (*params).len, ptr);
  uqbar_process_0_4_0_standard_option_signed_capability_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (uqbar_process_0_4_0_standard_signed_capability_t) {
        (uqbar_process_0_4_0_standard_address_t) {
          (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
          (uqbar_process_0_4_0_standard_process_id_t) {
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 20))), (size_t)(*((int32_t*) (ptr + 24))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 28))), (size_t)(*((int32_t*) (ptr + 32))) },
          },
        },
        (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 36))), (size_t)(*((int32_t*) (ptr + 40))) },
        (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 44))), (size_t)(*((int32_t*) (ptr + 48))) },
      };
      break;
    }
  }
  *ret = option;
}

void uqbar_process_0_4_0_standard_attach_capability(uqbar_process_0_4_0_standard_signed_capability_t *capability) {
  __wasm_import_uqbar_process_0_4_0_standard_attach_capability((int32_t) (((*capability).issuer).node).ptr, (int32_t) (((*capability).issuer).node).len, (int32_t) ((((*capability).issuer).process).process_name).ptr, (int32_t) ((((*capability).issuer).process).process_name).len, (int32_t) ((((*capability).issuer).process).package_name).ptr, (int32_t) ((((*capability).issuer).process).package_name).len, (int32_t) ((((*capability).issuer).process).publisher_node).ptr, (int32_t) ((((*capability).issuer).process).publisher_node).len, (int32_t) ((*capability).params).ptr, (int32_t) ((*capability).params).len, (int32_t) ((*capability).signature).ptr, (int32_t) ((*capability).signature).len);
}

void uqbar_process_0_4_0_standard_save_capabilities(uqbar_process_0_4_0_standard_list_signed_capability_t *capabilities) {
  __wasm_import_uqbar_process_0_4_0_standard_save_capabilities((int32_t) (*capabilities).ptr, (int32_t) (*capabilities).len);
}

bool uqbar_process_0_4_0_standard_has_capability(uqbar_process_0_4_0_standard_json_t *params) {
  int32_t ret = __wasm_import_uqbar_process_0_4_0_standard_has_capability((int32_t) (*params).ptr, (int32_t) (*params).len);
  return ret;
}

void uqbar_process_0_4_0_standard_create_capability(uqbar_process_0_4_0_standard_process_id_t *to, uqbar_process_0_4_0_standard_json_t *params) {
  __wasm_import_uqbar_process_0_4_0_standard_create_capability((int32_t) ((*to).process_name).ptr, (int32_t) ((*to).process_name).len, (int32_t) ((*to).package_name).ptr, (int32_t) ((*to).package_name).len, (int32_t) ((*to).publisher_node).ptr, (int32_t) ((*to).publisher_node).len, (int32_t) (*params).ptr, (int32_t) (*params).len);
}

void uqbar_process_0_4_0_standard_share_capability(uqbar_process_0_4_0_standard_process_id_t *to, uqbar_process_0_4_0_standard_signed_capability_t *capability) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[72];
  int32_t ptr = (int32_t) &ret_area;
  *((int32_t*)(ptr + 4)) = (int32_t) ((*to).process_name).len;
  *((int32_t*)(ptr + 0)) = (int32_t) ((*to).process_name).ptr;
  *((int32_t*)(ptr + 12)) = (int32_t) ((*to).package_name).len;
  *((int32_t*)(ptr + 8)) = (int32_t) ((*to).package_name).ptr;
  *((int32_t*)(ptr + 20)) = (int32_t) ((*to).publisher_node).len;
  *((int32_t*)(ptr + 16)) = (int32_t) ((*to).publisher_node).ptr;
  *((int32_t*)(ptr + 28)) = (int32_t) (((*capability).issuer).node).len;
  *((int32_t*)(ptr + 24)) = (int32_t) (((*capability).issuer).node).ptr;
  *((int32_t*)(ptr + 36)) = (int32_t) ((((*capability).issuer).process).process_name).len;
  *((int32_t*)(ptr + 32)) = (int32_t) ((((*capability).issuer).process).process_name).ptr;
  *((int32_t*)(ptr + 44)) = (int32_t) ((((*capability).issuer).process).package_name).len;
  *((int32_t*)(ptr + 40)) = (int32_t) ((((*capability).issuer).process).package_name).ptr;
  *((int32_t*)(ptr + 52)) = (int32_t) ((((*capability).issuer).process).publisher_node).len;
  *((int32_t*)(ptr + 48)) = (int32_t) ((((*capability).issuer).process).publisher_node).ptr;
  *((int32_t*)(ptr + 60)) = (int32_t) ((*capability).params).len;
  *((int32_t*)(ptr + 56)) = (int32_t) ((*capability).params).ptr;
  *((int32_t*)(ptr + 68)) = (int32_t) ((*capability).signature).len;
  *((int32_t*)(ptr + 64)) = (int32_t) ((*capability).signature).ptr;
  __wasm_import_uqbar_process_0_4_0_standard_share_capability(ptr);
}

void uqbar_process_0_4_0_standard_receive(uqbar_process_0_4_0_standard_result_tuple2_address_message_tuple2_send_error_option_context_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[112];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_receive(ptr);
  uqbar_process_0_4_0_standard_result_tuple2_address_message_tuple2_send_error_option_context_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      uqbar_process_0_4_0_standard_message_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 40)));
      switch ((int32_t) variant.tag) {
        case 0: {
          process_option_u64_t option;
          switch ((int32_t) (*((uint8_t*) (ptr + 56)))) {
            case 0: {
              option.is_some = false;
              break;
            }
            case 1: {
              option.is_some = true;
              option.val = (uint64_t) (*((int64_t*) (ptr + 64)));
              break;
            }
          }
          process_option_json_t option0;
          switch ((int32_t) (*((uint8_t*) (ptr + 80)))) {
            case 0: {
              option0.is_some = false;
              break;
            }
            case 1: {
              option0.is_some = true;
              option0.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 84))), (size_t)(*((int32_t*) (ptr + 88))) };
              break;
            }
          }
          variant.val.request = (uqbar_process_0_4_0_standard_request_t) {
            (int32_t) (*((uint8_t*) (ptr + 48))),
            option,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 72))), (size_t)(*((int32_t*) (ptr + 76))) },
            option0,
          };
          break;
        }
        case 1: {
          process_option_json_t option1;
          switch ((int32_t) (*((uint8_t*) (ptr + 60)))) {
            case 0: {
              option1.is_some = false;
              break;
            }
            case 1: {
              option1.is_some = true;
              option1.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 64))), (size_t)(*((int32_t*) (ptr + 68))) };
              break;
            }
          }
          process_option_context_t option2;
          switch ((int32_t) (*((uint8_t*) (ptr + 72)))) {
            case 0: {
              option2.is_some = false;
              break;
            }
            case 1: {
              option2.is_some = true;
              option2.val = (uqbar_process_0_4_0_standard_context_t) { (uint8_t*)(*((int32_t*) (ptr + 76))), (size_t)(*((int32_t*) (ptr + 80))) };
              break;
            }
          }
          variant.val.response = (uqbar_process_0_4_0_standard_tuple2_response_option_context_t) {
            (uqbar_process_0_4_0_standard_response_t) {
              (int32_t) (*((uint8_t*) (ptr + 48))),
              (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 52))), (size_t)(*((int32_t*) (ptr + 56))) },
              option1,
            },
            option2,
          };
          break;
        }
      }
      
      result.val.ok = (uqbar_process_0_4_0_standard_tuple2_address_message_t) {
        (uqbar_process_0_4_0_standard_address_t) {
          (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 8))), (size_t)(*((int32_t*) (ptr + 12))) },
          (uqbar_process_0_4_0_standard_process_id_t) {
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 24))), (size_t)(*((int32_t*) (ptr + 28))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 32))), (size_t)(*((int32_t*) (ptr + 36))) },
          },
        },
        variant,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      uqbar_process_0_4_0_standard_message_t variant7;
      variant7.tag = (int32_t) (*((uint8_t*) (ptr + 16)));
      switch ((int32_t) variant7.tag) {
        case 0: {
          process_option_u64_t option3;
          switch ((int32_t) (*((uint8_t*) (ptr + 32)))) {
            case 0: {
              option3.is_some = false;
              break;
            }
            case 1: {
              option3.is_some = true;
              option3.val = (uint64_t) (*((int64_t*) (ptr + 40)));
              break;
            }
          }
          process_option_json_t option4;
          switch ((int32_t) (*((uint8_t*) (ptr + 56)))) {
            case 0: {
              option4.is_some = false;
              break;
            }
            case 1: {
              option4.is_some = true;
              option4.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 60))), (size_t)(*((int32_t*) (ptr + 64))) };
              break;
            }
          }
          variant7.val.request = (uqbar_process_0_4_0_standard_request_t) {
            (int32_t) (*((uint8_t*) (ptr + 24))),
            option3,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 48))), (size_t)(*((int32_t*) (ptr + 52))) },
            option4,
          };
          break;
        }
        case 1: {
          process_option_json_t option5;
          switch ((int32_t) (*((uint8_t*) (ptr + 36)))) {
            case 0: {
              option5.is_some = false;
              break;
            }
            case 1: {
              option5.is_some = true;
              option5.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 40))), (size_t)(*((int32_t*) (ptr + 44))) };
              break;
            }
          }
          process_option_context_t option6;
          switch ((int32_t) (*((uint8_t*) (ptr + 48)))) {
            case 0: {
              option6.is_some = false;
              break;
            }
            case 1: {
              option6.is_some = true;
              option6.val = (uqbar_process_0_4_0_standard_context_t) { (uint8_t*)(*((int32_t*) (ptr + 52))), (size_t)(*((int32_t*) (ptr + 56))) };
              break;
            }
          }
          variant7.val.response = (uqbar_process_0_4_0_standard_tuple2_response_option_context_t) {
            (uqbar_process_0_4_0_standard_response_t) {
              (int32_t) (*((uint8_t*) (ptr + 24))),
              (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 28))), (size_t)(*((int32_t*) (ptr + 32))) },
              option5,
            },
            option6,
          };
          break;
        }
      }
      uqbar_process_0_4_0_standard_option_payload_t option9;
      switch ((int32_t) (*((uint8_t*) (ptr + 72)))) {
        case 0: {
          option9.is_some = false;
          break;
        }
        case 1: {
          option9.is_some = true;
          process_option_string_t option8;
          switch ((int32_t) (*((uint8_t*) (ptr + 76)))) {
            case 0: {
              option8.is_some = false;
              break;
            }
            case 1: {
              option8.is_some = true;
              option8.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 80))), (size_t)(*((int32_t*) (ptr + 84))) };
              break;
            }
          }
          
          option9.val = (uqbar_process_0_4_0_standard_payload_t) {
            option8,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 88))), (size_t)(*((int32_t*) (ptr + 92))) },
          };
          break;
        }
      }
      process_option_context_t option10;
      switch ((int32_t) (*((uint8_t*) (ptr + 96)))) {
        case 0: {
          option10.is_some = false;
          break;
        }
        case 1: {
          option10.is_some = true;
          option10.val = (uqbar_process_0_4_0_standard_context_t) { (uint8_t*)(*((int32_t*) (ptr + 100))), (size_t)(*((int32_t*) (ptr + 104))) };
          break;
        }
      }
      
      result.val.err = (uqbar_process_0_4_0_standard_tuple2_send_error_option_context_t) {
        (uqbar_process_0_4_0_standard_send_error_t) {
          (int32_t) (*((uint8_t*) (ptr + 8))),
          variant7,
          option9,
        },
        option10,
      };
      break;
    }
  }
  *ret = result;
}

void uqbar_process_0_4_0_standard_get_payload(uqbar_process_0_4_0_standard_option_payload_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_get_payload(ptr);
  uqbar_process_0_4_0_standard_option_payload_t option0;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option0.is_some = false;
      break;
    }
    case 1: {
      option0.is_some = true;
      process_option_string_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 4)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr + 8))), (size_t)(*((int32_t*) (ptr + 12))) };
          break;
        }
      }
      
      option0.val = (uqbar_process_0_4_0_standard_payload_t) {
        option,
        (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) },
      };
      break;
    }
  }
  *ret = option0;
}

void uqbar_process_0_4_0_standard_send_request(uqbar_process_0_4_0_standard_address_t *target, uqbar_process_0_4_0_standard_request_t *request, process_option_context_t *context, uqbar_process_0_4_0_standard_option_payload_t *payload) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[120];
  int32_t ptr = (int32_t) &ret_area;
  *((int32_t*)(ptr + 4)) = (int32_t) ((*target).node).len;
  *((int32_t*)(ptr + 0)) = (int32_t) ((*target).node).ptr;
  *((int32_t*)(ptr + 12)) = (int32_t) (((*target).process).process_name).len;
  *((int32_t*)(ptr + 8)) = (int32_t) (((*target).process).process_name).ptr;
  *((int32_t*)(ptr + 20)) = (int32_t) (((*target).process).package_name).len;
  *((int32_t*)(ptr + 16)) = (int32_t) (((*target).process).package_name).ptr;
  *((int32_t*)(ptr + 28)) = (int32_t) (((*target).process).publisher_node).len;
  *((int32_t*)(ptr + 24)) = (int32_t) (((*target).process).publisher_node).ptr;
  *((int8_t*)(ptr + 32)) = (*request).inherit;
  if (((*request).expects_response).is_some) {
    const uint64_t *payload1 = &((*request).expects_response).val;
    *((int8_t*)(ptr + 40)) = 1;
    *((int64_t*)(ptr + 48)) = (int64_t) (*payload1);
  } else {
    *((int8_t*)(ptr + 40)) = 0;
  }
  *((int32_t*)(ptr + 60)) = (int32_t) ((*request).ipc).len;
  *((int32_t*)(ptr + 56)) = (int32_t) ((*request).ipc).ptr;
  if (((*request).metadata).is_some) {
    const uqbar_process_0_4_0_standard_json_t *payload3 = &((*request).metadata).val;
    *((int8_t*)(ptr + 64)) = 1;
    *((int32_t*)(ptr + 72)) = (int32_t) (*payload3).len;
    *((int32_t*)(ptr + 68)) = (int32_t) (*payload3).ptr;
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  if ((*context).is_some) {
    const uqbar_process_0_4_0_standard_context_t *payload5 = &(*context).val;
    *((int8_t*)(ptr + 80)) = 1;
    *((int32_t*)(ptr + 88)) = (int32_t) (*payload5).len;
    *((int32_t*)(ptr + 84)) = (int32_t) (*payload5).ptr;
  } else {
    *((int8_t*)(ptr + 80)) = 0;
  }
  if ((*payload).is_some) {
    const uqbar_process_0_4_0_standard_payload_t *payload7 = &(*payload).val;
    *((int8_t*)(ptr + 92)) = 1;
    if (((*payload7).mime).is_some) {
      const process_string_t *payload9 = &((*payload7).mime).val;
      *((int8_t*)(ptr + 96)) = 1;
      *((int32_t*)(ptr + 104)) = (int32_t) (*payload9).len;
      *((int32_t*)(ptr + 100)) = (int32_t) (*payload9).ptr;
    } else {
      *((int8_t*)(ptr + 96)) = 0;
    }
    *((int32_t*)(ptr + 112)) = (int32_t) ((*payload7).bytes).len;
    *((int32_t*)(ptr + 108)) = (int32_t) ((*payload7).bytes).ptr;
  } else {
    *((int8_t*)(ptr + 92)) = 0;
  }
  __wasm_import_uqbar_process_0_4_0_standard_send_request(ptr);
}

void uqbar_process_0_4_0_standard_send_requests(uqbar_process_0_4_0_standard_list_tuple4_address_request_option_context_option_payload_t *requests) {
  __wasm_import_uqbar_process_0_4_0_standard_send_requests((int32_t) (*requests).ptr, (int32_t) (*requests).len);
}

void uqbar_process_0_4_0_standard_send_response(uqbar_process_0_4_0_standard_response_t *response, uqbar_process_0_4_0_standard_option_payload_t *payload) {
  int32_t option;
  int32_t option2;
  int32_t option3;
  if (((*response).metadata).is_some) {
    const uqbar_process_0_4_0_standard_json_t *payload1 = &((*response).metadata).val;
    option = 1;
    option2 = (int32_t) (*payload1).ptr;
    option3 = (int32_t) (*payload1).len;
  } else {
    option = 0;
    option2 = 0;
    option3 = 0;
  }
  int32_t option11;
  int32_t option12;
  int32_t option13;
  int32_t option14;
  int32_t option15;
  int32_t option16;
  if ((*payload).is_some) {
    const uqbar_process_0_4_0_standard_payload_t *payload5 = &(*payload).val;
    int32_t option8;
    int32_t option9;
    int32_t option10;
    if (((*payload5).mime).is_some) {
      const process_string_t *payload7 = &((*payload5).mime).val;
      option8 = 1;
      option9 = (int32_t) (*payload7).ptr;
      option10 = (int32_t) (*payload7).len;
    } else {
      option8 = 0;
      option9 = 0;
      option10 = 0;
    }
    option11 = 1;
    option12 = option8;
    option13 = option9;
    option14 = option10;
    option15 = (int32_t) ((*payload5).bytes).ptr;
    option16 = (int32_t) ((*payload5).bytes).len;
  } else {
    option11 = 0;
    option12 = 0;
    option13 = 0;
    option14 = 0;
    option15 = 0;
    option16 = 0;
  }
  __wasm_import_uqbar_process_0_4_0_standard_send_response((*response).inherit, (int32_t) ((*response).ipc).ptr, (int32_t) ((*response).ipc).len, option, option2, option3, option11, option12, option13, option14, option15, option16);
}

void uqbar_process_0_4_0_standard_send_and_await_response(uqbar_process_0_4_0_standard_address_t *target, uqbar_process_0_4_0_standard_request_t *request, uqbar_process_0_4_0_standard_option_payload_t *payload, uqbar_process_0_4_0_standard_result_tuple2_address_message_send_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[104];
  int32_t ptr = (int32_t) &ret_area;
  *((int32_t*)(ptr + 4)) = (int32_t) ((*target).node).len;
  *((int32_t*)(ptr + 0)) = (int32_t) ((*target).node).ptr;
  *((int32_t*)(ptr + 12)) = (int32_t) (((*target).process).process_name).len;
  *((int32_t*)(ptr + 8)) = (int32_t) (((*target).process).process_name).ptr;
  *((int32_t*)(ptr + 20)) = (int32_t) (((*target).process).package_name).len;
  *((int32_t*)(ptr + 16)) = (int32_t) (((*target).process).package_name).ptr;
  *((int32_t*)(ptr + 28)) = (int32_t) (((*target).process).publisher_node).len;
  *((int32_t*)(ptr + 24)) = (int32_t) (((*target).process).publisher_node).ptr;
  *((int8_t*)(ptr + 32)) = (*request).inherit;
  if (((*request).expects_response).is_some) {
    const uint64_t *payload1 = &((*request).expects_response).val;
    *((int8_t*)(ptr + 40)) = 1;
    *((int64_t*)(ptr + 48)) = (int64_t) (*payload1);
  } else {
    *((int8_t*)(ptr + 40)) = 0;
  }
  *((int32_t*)(ptr + 60)) = (int32_t) ((*request).ipc).len;
  *((int32_t*)(ptr + 56)) = (int32_t) ((*request).ipc).ptr;
  if (((*request).metadata).is_some) {
    const uqbar_process_0_4_0_standard_json_t *payload3 = &((*request).metadata).val;
    *((int8_t*)(ptr + 64)) = 1;
    *((int32_t*)(ptr + 72)) = (int32_t) (*payload3).len;
    *((int32_t*)(ptr + 68)) = (int32_t) (*payload3).ptr;
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  if ((*payload).is_some) {
    const uqbar_process_0_4_0_standard_payload_t *payload5 = &(*payload).val;
    *((int8_t*)(ptr + 80)) = 1;
    if (((*payload5).mime).is_some) {
      const process_string_t *payload7 = &((*payload5).mime).val;
      *((int8_t*)(ptr + 84)) = 1;
      *((int32_t*)(ptr + 92)) = (int32_t) (*payload7).len;
      *((int32_t*)(ptr + 88)) = (int32_t) (*payload7).ptr;
    } else {
      *((int8_t*)(ptr + 84)) = 0;
    }
    *((int32_t*)(ptr + 100)) = (int32_t) ((*payload5).bytes).len;
    *((int32_t*)(ptr + 96)) = (int32_t) ((*payload5).bytes).ptr;
  } else {
    *((int8_t*)(ptr + 80)) = 0;
  }
  int32_t ptr8 = (int32_t) &ret_area;
  __wasm_import_uqbar_process_0_4_0_standard_send_and_await_response(ptr, ptr8);
  uqbar_process_0_4_0_standard_result_tuple2_address_message_send_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr8 + 0)))) {
    case 0: {
      result.is_err = false;
      uqbar_process_0_4_0_standard_message_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr8 + 40)));
      switch ((int32_t) variant.tag) {
        case 0: {
          process_option_u64_t option;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 56)))) {
            case 0: {
              option.is_some = false;
              break;
            }
            case 1: {
              option.is_some = true;
              option.val = (uint64_t) (*((int64_t*) (ptr8 + 64)));
              break;
            }
          }
          process_option_json_t option9;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 80)))) {
            case 0: {
              option9.is_some = false;
              break;
            }
            case 1: {
              option9.is_some = true;
              option9.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 84))), (size_t)(*((int32_t*) (ptr8 + 88))) };
              break;
            }
          }
          variant.val.request = (uqbar_process_0_4_0_standard_request_t) {
            (int32_t) (*((uint8_t*) (ptr8 + 48))),
            option,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr8 + 72))), (size_t)(*((int32_t*) (ptr8 + 76))) },
            option9,
          };
          break;
        }
        case 1: {
          process_option_json_t option10;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 60)))) {
            case 0: {
              option10.is_some = false;
              break;
            }
            case 1: {
              option10.is_some = true;
              option10.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 64))), (size_t)(*((int32_t*) (ptr8 + 68))) };
              break;
            }
          }
          process_option_context_t option11;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 72)))) {
            case 0: {
              option11.is_some = false;
              break;
            }
            case 1: {
              option11.is_some = true;
              option11.val = (uqbar_process_0_4_0_standard_context_t) { (uint8_t*)(*((int32_t*) (ptr8 + 76))), (size_t)(*((int32_t*) (ptr8 + 80))) };
              break;
            }
          }
          variant.val.response = (uqbar_process_0_4_0_standard_tuple2_response_option_context_t) {
            (uqbar_process_0_4_0_standard_response_t) {
              (int32_t) (*((uint8_t*) (ptr8 + 48))),
              (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr8 + 52))), (size_t)(*((int32_t*) (ptr8 + 56))) },
              option10,
            },
            option11,
          };
          break;
        }
      }
      
      result.val.ok = (uqbar_process_0_4_0_standard_tuple2_address_message_t) {
        (uqbar_process_0_4_0_standard_address_t) {
          (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 8))), (size_t)(*((int32_t*) (ptr8 + 12))) },
          (uqbar_process_0_4_0_standard_process_id_t) {
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 16))), (size_t)(*((int32_t*) (ptr8 + 20))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 24))), (size_t)(*((int32_t*) (ptr8 + 28))) },
            (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 32))), (size_t)(*((int32_t*) (ptr8 + 36))) },
          },
        },
        variant,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      uqbar_process_0_4_0_standard_message_t variant16;
      variant16.tag = (int32_t) (*((uint8_t*) (ptr8 + 16)));
      switch ((int32_t) variant16.tag) {
        case 0: {
          process_option_u64_t option12;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 32)))) {
            case 0: {
              option12.is_some = false;
              break;
            }
            case 1: {
              option12.is_some = true;
              option12.val = (uint64_t) (*((int64_t*) (ptr8 + 40)));
              break;
            }
          }
          process_option_json_t option13;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 56)))) {
            case 0: {
              option13.is_some = false;
              break;
            }
            case 1: {
              option13.is_some = true;
              option13.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 60))), (size_t)(*((int32_t*) (ptr8 + 64))) };
              break;
            }
          }
          variant16.val.request = (uqbar_process_0_4_0_standard_request_t) {
            (int32_t) (*((uint8_t*) (ptr8 + 24))),
            option12,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr8 + 48))), (size_t)(*((int32_t*) (ptr8 + 52))) },
            option13,
          };
          break;
        }
        case 1: {
          process_option_json_t option14;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 36)))) {
            case 0: {
              option14.is_some = false;
              break;
            }
            case 1: {
              option14.is_some = true;
              option14.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 40))), (size_t)(*((int32_t*) (ptr8 + 44))) };
              break;
            }
          }
          process_option_context_t option15;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 48)))) {
            case 0: {
              option15.is_some = false;
              break;
            }
            case 1: {
              option15.is_some = true;
              option15.val = (uqbar_process_0_4_0_standard_context_t) { (uint8_t*)(*((int32_t*) (ptr8 + 52))), (size_t)(*((int32_t*) (ptr8 + 56))) };
              break;
            }
          }
          variant16.val.response = (uqbar_process_0_4_0_standard_tuple2_response_option_context_t) {
            (uqbar_process_0_4_0_standard_response_t) {
              (int32_t) (*((uint8_t*) (ptr8 + 24))),
              (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr8 + 28))), (size_t)(*((int32_t*) (ptr8 + 32))) },
              option14,
            },
            option15,
          };
          break;
        }
      }
      uqbar_process_0_4_0_standard_option_payload_t option18;
      switch ((int32_t) (*((uint8_t*) (ptr8 + 72)))) {
        case 0: {
          option18.is_some = false;
          break;
        }
        case 1: {
          option18.is_some = true;
          process_option_string_t option17;
          switch ((int32_t) (*((uint8_t*) (ptr8 + 76)))) {
            case 0: {
              option17.is_some = false;
              break;
            }
            case 1: {
              option17.is_some = true;
              option17.val = (process_string_t) { (uint8_t*)(*((int32_t*) (ptr8 + 80))), (size_t)(*((int32_t*) (ptr8 + 84))) };
              break;
            }
          }
          
          option18.val = (uqbar_process_0_4_0_standard_payload_t) {
            option17,
            (process_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr8 + 88))), (size_t)(*((int32_t*) (ptr8 + 92))) },
          };
          break;
        }
      }
      
      result.val.err = (uqbar_process_0_4_0_standard_send_error_t) {
        (int32_t) (*((uint8_t*) (ptr8 + 8))),
        variant16,
        option18,
      };
      break;
    }
  }
  *ret = result;
}

__attribute__((__export_name__("init")))
void __wasm_export_process_init(int32_t arg, int32_t arg0) {
  process_string_t arg1 = (process_string_t) { (uint8_t*)(arg), (size_t)(arg0) };
  process_init(&arg1);
}

extern void __component_type_object_force_link_process(void);
void __component_type_object_force_link_process_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_process();
}
